spring:
  application:
    name: demo  #服务名称
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: druid
  servlet:
    # 限制上传文件大小
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  # 文件路径
  profile: /home
# 测试环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 81

# 日志配置
logging:
  level:
    com.rynat.workorder: info
    org.springframework: warn

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.demo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

tg:
  token: 6368180811:AAGQ_VcnrAnMNnLIHH9cKWu5i3mb_a8kn70
  username: guangdongCpBot
